orms/wedding_planner/Models/Wedding.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;

namespace wedding_planner.Models
{
    public class Wedding
    {
        [Key]
        public int WeddingId {get; set;}
        [Required]
        [Display(Name ="Wedder One")]
        public string WedderOne {get; set;}
        [Required]
        [Display(Name ="Wedder Two")]
        public string WedderTwo {get; set;}
        [Required]
        [FutureDate]
        public DateTime Date {get; set;}
        [Required]
        public string Address {get; set;}
        [Required]
        public int UserId {get; set;}
        public User? Creator {get; set;}
        public DateTime CreatedAt {get; set;} = DateTime.Now;
        public DateTime UpdatedAt {get; set;} = DateTime.Now;
        public List<Attendee> Attendees {get; set;} = new List<Attendee>();

        public class FutureDateAttribute : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                DateTime date = (DateTime)value;
                DateTime today = DateTime.Today;
                if(date < today)
                {
                    return new ValidationResult("Date must be a future date");
                }
                return ValidationResult.Success;
            }
        }
    }
}

orms/wedding_planner/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using wedding_planner.Models;
using Microsoft.EntityFrameworkCore;

namespace wedding_planner.Controllers;

public class HomeController : Controller
    {
    private MyContext _context;

    public HomeController(MyContext context)
    {
        _context = context;
    }
    [HttpGet("")]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("dashboard")]
    public IActionResult Dashboard()
    {
        if(HttpContext.Session.GetInt32("UserId") == null)
        {
            return RedirectToAction("Index");
        }
        else
        {
            User user = _context.Users
            .Include(u => u.Weddings)
            .ThenInclude(w => w.Wedding)
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

            List<Wedding> weddings = _context.Weddings
            .Include(w => w.Attendees)
            .ThenInclude(a => a.User)
            .ToList();

            ViewBag.User = user;
            ViewBag.Weddings = weddings;
            return View();
        }
    }

    [HttpGet("weddings/new")]
    public IActionResult NewWedding()
    {
        if(HttpContext.Session.GetInt32("UserId") == null)
        {
            return RedirectToAction("Index");
        }
        else
        {
            return View();
        }
    }

    [HttpGet("/weddings/{WeddingId}")]
    public IActionResult Wedding(int WeddingId)
    {
        Wedding weddingInDb = _context.Weddings
        .Include(w => w.Attendees)
        .ThenInclude(a => a.User)
        .FirstOrDefault(w => w.WeddingId == WeddingId);

        if(weddingInDb != null)
        {
            ViewBag.Wedding = weddingInDb;
            return View();
        }
        else
        {
            return Redirect("/dashboard");
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

orms/wedding_planner/Controllers/WeddingController.cs
using Microsoft.AspNetCore.Mvc;

using wedding_planner.Models;
namespace wedding_planner.Controllers;

public class WeddingController : Controller
    {
    private MyContext _context;

    public WeddingController(MyContext context)
    {
        _context = context;
    }

    [HttpPost]
    public IActionResult SaveWedding(Wedding newWedding)
    {
        if(ModelState.IsValid)
        {
            _context.Add(newWedding);
            _context.SaveChanges();

            Attendee newAttendee = new Attendee();
            newAttendee.UserId = newWedding.UserId;
            newAttendee.WeddingId = newWedding.WeddingId;
            _context.Add(newAttendee);
            _context.SaveChanges();

            return Redirect("/dashboard");
        }
        else
        {
            return View("../Home/NewWedding");
        }
    }

    [HttpGet("weddings/delete/{WeddingId}")]
    public IActionResult DeleteWedding(int WeddingId)
    {
        Wedding wedding = _context.Weddings.FirstOrDefault(w => w.WeddingId == WeddingId);
        if(wedding == null || wedding.UserId != HttpContext.Session.GetInt32("UserId"))
        {
            return Redirect("/dashboard");
        }
        else
        {
            _context.Weddings.Remove(wedding);
            _context.SaveChanges();
            return Redirect("/dashboard");
        }
    }
}

orms/wedding_planner/Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<div class="d-flex justify-content-between w-100 mt-5 mb-5">
    <h1 class="display-4">Welcome to the Wedding Planner, @ViewBag.User.FirstName!</h1>
    <a class="align-self-center" href="/logout">Logout</a>
</div>
<table class="table table-striped">
    <thead>
        <th scope="col">Wedding</th>
        <th scope="col">Date</th>
        <th scope="col">Guests</th>
        <th scope="col">Action</th>
    </thead>
    <tbody>
        @{
            foreach(var wedding in ViewBag.Weddings)
            {
                <tr>
                    <td><a href="/weddings/@wedding.WeddingId">@wedding.WedderOne & @wedding.WedderTwo</a></td>
                    <td>@wedding.Date.ToString("MMM dd yyyy")</td>
                    <td>@wedding.Attendees.Count</td>
                    @{
                        if(wedding.UserId == ViewBag.User.UserId)
                        {
                            <td><a href="/weddings/delete/@wedding.WeddingId">Delete</a></td>
                        }
                        else
                        {
                            List<Attendee> attendees = wedding.Attendees;
                            bool inAttendees = attendees.Exists(a => a.User.UserId == ViewBag.User.UserId);
                            if(inAttendees)
                            {
                                Attendee attendee = attendees.Find(a => a.UserId == ViewBag.User.UserId && a.WeddingId == wedding.WeddingId);
                                <td><a href="/un-rsvp/@attendee.AttendeeId">un-RSVP</a></td>
                            }
                            else
                            {
                                <td><a href="/rsvp/@ViewBag.User.UserId/@wedding.WeddingId">RSVP</a></td>
                            }
                        }
                    }
                </tr>
            }
        }
    </tbody>
</table>
<div class="d-flex w-100 justify-content-end">
    <a href="/weddings/new"><button class="btn btn-secondary">Create Wedding</button></a>
</div>

orms/wedding_planner/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Register | Login";
}

<div class="row justify-content-center mt-5">
    <div class="col-6">
        <h1 class="display-4 mb-5">Register</h1>
        <partial name="_registerForm" />
    </div>
    <div class="col-6">
        <h1 class="display-4 mb-5">Login</h1>
        <partial name="_loginForm" />
    </div>
</div>

orms/wedding_planner/Views/Home/NewWedding.cshtml
@{
    ViewData["Title"] = "Plan Wedding";
}

@model Wedding;
@using Microsoft.AspNetCore.Http;
@{
    int UserId = (int)Context.Session.GetInt32("UserId");
}

<div class="d-flex justify-content-between w-100 mt-5 mb-5">
    <h1 class="display-4">Plan Your Wedding</h1>
    <div class="align-self-center">
        <a href="/dashboard">Dashboard</a>
        <a href="/logout">Logout</a>
    </div>
</div>
<form asp-action="SaveWedding" asp-controller="Wedding">
    <input type="hidden" asp-for="UserId" value="@UserId">
    <div class="row">
        <div class="col-3">
            <label class="col-form-label" asp-for="WedderOne"></label>
        </div>
        <div class="col-5">
            <input class="form-control" asp-for="WedderOne">
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-3">
        </div>
        <div class="col">
            <small><span class="text-danger" asp-validation-for="WedderOne"></span></small>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <label class="col-form-label" asp-for="WedderTwo"></label>
        </div>
        <div class="col-5">
            <input class="form-control" asp-for="WedderTwo">
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-3">
        </div>
        <div class="col">
            <small><span class="text-danger" asp-validation-for="WedderTwo"></span></small>
        </div>
    </div>
        <div class="row">
        <div class="col-3">
            <label class="col-form-label" asp-for="Date"></label>
        </div>
        <div class="col-2">
            <input type="date" class="form-control" asp-for="Date">
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-3">
        </div>
        <div class="col">
            <small><span class="text-danger" asp-validation-for="Date"></span></small>
        </div>
    </div>
        <div class="row">
        <div class="col-3">
            <label class="col-form-label" asp-for="Address"></label>
        </div>
        <div class="col-5">
            <input class="form-control" asp-for="Address">
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-3">
        </div>
        <div class="col">
            <small><span class="text-danger" asp-validation-for="Address"></span></small>
        </div>
    </div>
    <div class="row">
        <div class="col-8 text-end">
            <input class="btn btn-primary" type="submit" value="Create">
        </div>
    </div>
</form>

orms/wedding_planner/Views/Home/Wedding.cshtml
@{
    ViewData["Title"] = "Plan Wedding";
}

<div class="d-flex justify-content-between w-100 mt-5 mb-5">
    <h1 class="display-4">@ViewBag.Wedding.WedderOne and @ViewBag.Wedding.WedderTwo's Wedding</h1>
    <div class="align-self-center">
        <a href="/dashboard">Dashboard</a>
        <a href="/logout">Logout</a>
    </div>
</div>
<h1 class="display-6 mb-5">Date: @ViewBag.Wedding.Date.ToString("MMMM dd, yyyy")</h1>
<h1 class="display-6 mb-3">Guests:</h1>
<ul>
    @{
        foreach(var attendee in ViewBag.Wedding.Attendees)
        {
            <li>@attendee.User.FirstName @attendee.User.LastName</li>
        }
    }
</ul>